Merge branch 'master' of https://github.com/Somibandaru/animal-game
TechForAutismDyslexia/animal-joining-game pull request #2
Opened 2024-07-05 17:57 UTC by Somibandaru

Fixes #1

2024-07-06 04:24 UTC, Jai-JAP requested changes
rename `index.js` and `App.js` to have `.jsx` extension

2024-07-06 04:25 UTC, Jai-JAP commented on public/index.html
>    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js"></script>
This is not needed as you import canvas confetti in react

2024-07-06 11:31 UTC, Jai-JAP approved these changes

2024-07-07 08:21 UTC, brohithkr approved these changes

2024-07-07 08:22 UTC, merged